name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarQube Scanner
        run: |
          ./sonar-scanner/bin/sonar-scanner.bat
